Add documentation for march_shared_classes
project-march/tutorials pull request #124
Opened 2020-03-25 15:42 UTC by Roelemans

Closes PM-353

## Description

Add documentation on March Shared classes. They were build really well so this is all you really need to know for basic usage. I think it would be more easier if they look at the (well-commented) code for more complicated usage. What do y'all think?

## Changes

* Added documentation for march_shared_classes

2020-03-26 10:09 UTC, Olavhaasie requested changes
You also need the page to the index.rst toc

2020-03-26 10:09 UTC, Olavhaasie commented on doc/march_packages/march_shared_classes.rst
> +================
This fails your build lol
```suggestion
march_shared_classes
====================
```

2020-03-26 14:51 UTC, Joris-JW approved these changes

2020-03-27 09:18 UTC, Olavhaasie approved these changes

2020-03-27 09:25 UTC, merged