Add imu manager package documentation
project-march/tutorials pull request #126
Opened 2020-03-26 12:53 UTC by RutgerVanBeek

Closes PM-354

## Description

This adds the documentation on the IMU manager to the documentation on our packages. It describes how you can use it and how it interacts with the IMU, ROS and tf2. Furthermore it gives some options to try, when you have problems with connecting with the IMU. 
## Changes

* Add a page on the march_imu_manager package

2020-03-26 14:59 UTC, JorisWeeda commented on doc/march_packages/march_imu_manager.rst
> +The IMU's connect wireless to an USB dongle, which should be inserted in the computer the node is running on.
```suggestion
The IMU's connect wireless to an USB dongle, which should be inserted in the computer before the node is launched.
```

2020-03-26 15:02 UTC, Joris-JW requested changes
small comment on inserting the usb dongle before launching the node.

2020-03-26 19:47 UTC, Joris-JW approved these changes

2020-03-27 09:17 UTC, Olavhaasie approved these changes

2020-03-27 09:17 UTC, merged