Gait selection develop
project-march/tutorials pull request #155
Opened 2020-08-25 15:18 UTC by Olavhaasie

## Description
Changes the documentation to reflect the changes made in project-march/march#538.

## Changes
* Add new architecture diagram
* Remove `march_state_machine` and SMACH pages
* Add section on how to create a gait file
* Add docs on new gait selection

2020-08-25 18:23 UTC, RutgerVanBeek requested changes
One really tiny change

2020-08-25 18:23 UTC, RutgerVanBeek commented on doc/march_packages/march_gait_selection.rst
> +input device. If the gait is accepted by the state machine, the requested gait
```suggestion
The gait state machine accepts or declines a gait request originating from an
input device. If the gait is accepted by the state machine, the requested gait
```

2020-08-26 07:37 UTC, RutgerVanBeek approved these changes

2020-08-28 15:10 UTC, Roelemans approved these changes

2020-09-16 09:05 UTC, merged