Feature/pm 88 testing tutorials
project-march/tutorials pull request #98
Opened 2019-10-30 07:52 UTC by Olavhaasie

Closes PM-88

## Description
Add a tutorial of running tests locally and how to write unit tests in python and c++ with a tutorial.

## Changes
* Added `ros_test_tutorial` subproject with some python and c++ library code
* Added `testing.rst` page

Please read the tutorials 😇

2019-10-30 14:18 UTC, RutgerVanBeek requested changes

2019-10-30 14:18 UTC, RutgerVanBeek commented on doc/development/testing.rst
> +`roslint <https://wiki.ros.org/roslint>`_. The ``roslint`` target should also
packages that contain what?

2019-10-30 14:18 UTC, RutgerVanBeek commented on doc/development/testing.rst
> +
It is nice to have C++ with capital letter everywhere.

2019-10-30 14:18 UTC, RutgerVanBeek commented on doc/development/testing.rst
> +
Are you going to do this in the future and is there already an issue for this?

2019-10-30 14:18 UTC, RutgerVanBeek commented on doc/development/testing.rst
> +
Are you going to do this in the future and is there already an issue for this?

2019-10-30 14:22 UTC, RutgerVanBeek commented on doc/development/testing.rst
> +This command will run the ``roslint`` target on any packages that use
Add the option --event-handlers console_direct+ to see lint warnings

2019-10-30 15:37 UTC, Roelemans requested changes
Nice job. A few comments and some questions

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +tests fail. Colcon also gives the possibility to review the test results and
Here it seems like "build" runs all tests and will fail when tests fail.

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +4. Do not depend on timing in your tests.
'Vo

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +``package.xml``.
```suggestion
``package.xml`` for this repository, so this is not necessary in this example.
```

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +Tests are always located in the ``test/`` directory of a package. To create a
```suggestion
As an example we will create tests for the function Add.cpp that is located in this repository. Tests are always located in the ``test/`` directory of a package.  To create a
```

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +        catkin_add_gtest(add_test test/AddTest.cpp)
I do not understand what "add_test" means

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +Writing c++ node tests
Was this not also part of the issue?

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +Tests for python are also always located in the ``test/`` directory. We will
```suggestion
As an example we will create tests for the function Multiply.py that is located in this repository. Tests are also always located in the ``test/`` directory. We will
```

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +        rosunit.unitrun(PKG, 'test_multiply', MultiplyTest)
What does 'test_multiply' mean? Is that just a string that is displayed? Also, how does rosunit.unitrun now which functions in MultiplyTest are testfunctions it should run? (Does it run all functions, or all that start with "test" or something)

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +Next we must tell ``cmake`` to build and how to run the tests. We do this by
What do you mean "how to run don't you just tell it to build them?

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +        catkin_add_nosetests(test/MultiplyTest.py)
So this command is for python what 
catkin_add_gtest(add_test test/AddTest.cpp)
target_link_libraries(add_test ros_test_tutorial ${catkin_LIBRARIES})
is for c++?

2019-10-30 15:37 UTC, Roelemans commented on doc/development/testing.rst
> +The tests can also be run with ``colcon test``.
```suggestion
After building, the tests can now be run with ``colcon test``.
```

2019-10-30 16:55 UTC, Olavhaasie commented on doc/development/testing.rst
> +
Yes: PM-109

2019-10-30 16:56 UTC, Olavhaasie commented on doc/development/testing.rst
> +
PM-109

2019-10-30 17:10 UTC, Olavhaasie commented on doc/development/testing.rst
> +        catkin_add_nosetests(test/MultiplyTest.py)
Exactly

2019-10-31 08:39 UTC, RutgerVanBeek submitted a review, later dismissed

2019-10-31 08:54 UTC, Roelemans commented on doc/development/testing.rst
> +located in this repository. Tests are also always located in the ``test/``
```suggestion
located in this repository. Tests are always located in the ``test/``
```

2019-10-31 09:00 UTC, Roelemans approved these changes
Excellent job. This is very useful :)

2019-10-31 09:40 UTC, RutgerVanBeek approved these changes

2019-10-31 09:40 UTC, merged